export const movies = [
    {
        id: 1,
        name: "Ram Setu",
        backImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2Framsetubanner.png?alt=media&token=a4f6a02a-f794-4d4a-a532-1fdb393533df",
        fontImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FramsetuFont.png?alt=media&token=a85a29b7-2417-430c-8588-71dd374ee092",
        ratting: "4",
        year: "2022",
        length: "2:30:00",
        director: "Abhishek Sharma",
        cast: "Akshay Kumar, Jacqueline Fernandez, Nushrratt Bharuccha,Pravessh Rana",
        movieDesc: "It is the story of an archaeologist, who has set out to check out whether the Ram Setu bridge is a myth or a reality.",
        type: ["Latest", "Banner"],
        tag: "The Best Movies and Series to Watch in October"
    },
    {
        id: 5,
        name: "Godfather",
        backImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FgodFatherBack.png?alt=media&token=1868e584-83e8-44ed-8f6c-4ed149e37208",
        fontImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FgodFatherFont.png?alt=media&token=79738698-c559-485e-aea3-d7277f888bdb",
        ratting: "5",
        year: "2022",
        length: "2:10:00",
        director: "Mohan Raja",
        cast: "Chiranjeevi, Salman Khan, Nayanthara",
        movieDesc: "After the death of a political leader, a mysterious man steps in to ascend the throne.",
        type: ["Latest", "Banner", "Featured"],
        tag: "The Best Movies and Series to Watch"
    },
    {
        id: 2,
        name: "Ram Setu",
        backImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2Framsetubanner.png?alt=media&token=a4f6a02a-f794-4d4a-a532-1fdb393533df",
        fontImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FramsetuFont.png?alt=media&token=a85a29b7-2417-430c-8588-71dd374ee092",
        ratting: "4",
        year: "2022",
        length: "2:30:00",
        director: "Abhishek Sharma",
        cast: "Akshay Kumar, Jacqueline Fernandez, Nushrratt Bharuccha,Pravessh Rana",
        movieDesc: "It is the story of an archaeologist, who has set out to check out whether the Ram Setu bridge is a myth or a reality.",
        type: ["Latest", "Banner", "Featured"],
        tag: "The Best Movies and Series to Watch in October"
    },
    {
        id: 4,
        name: "Brahmastra",
        backImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FbramhaAstraBack.png?alt=media&token=12dfa7ef-c387-4681-8444-6a263cc760ba",
        fontImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FBrahmastraFont.jpeg?alt=media&token=bdbedfa2-ba48-4f28-a781-a2414add7abd",
        ratting: "5",
        year: "2022",
        length: "2:20:00",
        director: "Arjun",
        cast: "Alia Bhatt, Ranbir Kapoor",
        movieDesc: "The stars of 'Brahmastra Part One: Shiva' reveal when they first became fans of each other's work, how this film became a part of their DNA, and why their director won't tell them all the plot points in the forthcoming sequel.",
        type: ["Latest", "Banner"],
        tag: "The Best Movies and Series to Watch"
    },
    {
        id: 6,
        name: "Yellowstone",
        backImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FYellowstone.png?alt=media&token=0e6997f6-bfd5-4dac-be15-34506656cc8c",
        fontImage: "https://firebasestorage.googleapis.com/v0/b/foody-bef0b.appspot.com/o/demo%2FYellowstoneFont.png?alt=media&token=fe616e1d-d8ed-4bfa-83f5-4bc054e7db7a",
        ratting: "4",
        year: "2021",
        length: "2:10:00",
        director: "Nilesh",
        cast: "Kevin Costner, Luke Grimes, Kelly Reilly",
        movieDesc: "A ranching family in Montana faces off against others encroaching on their land.",
        type: ["Latest", "Banner", "Featured"],
        tag: "The Best Movies and Series to Watch"
    },
]